language: generic
env:
  global:
    - IDE_VERSION=1.8.5
  matrix:
    - BOARD="arduino:samd:mkrwifi1010"
    - BOARD="arduino:samd_beta:mkrvidor4000"
    - BOARD="arduino:megaavr:uno2018:mode=on"
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino --install-boards arduino:samd;
    fi
  - if [[ "$BOARD" =~ "arduino:samd_beta:" ]]; then
      arduino --install-boards arduino:samd_beta;
      arduino --install-library VidorPeripherals;
    fi
  - if [[ "$BOARD" =~ "arduino:megaavr:" ]]; then
      arduino --install-boards arduino:megaavr;
    fi
  - buildExampleSketch() { arduino --verbose-build --verify --board $BOARD $PWD/examples/$1/$1.ino; }
  - buildExampleToolsSketch() { arduino --verbose-build --verify --board $BOARD $PWD/examples/Tools/$1/$1.ino; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - buildExampleSketch AP_SimpleWebServer
  - buildExampleSketch ConnectNoEncryption
  - buildExampleSketch ConnectWithWEP
  - buildExampleSketch ConnectWithWPA
  - buildExampleSketch ScanNetworks
  - buildExampleSketch ScanNetworksAdvanced
  - buildExampleSketch SimpleWebServerWiFi
  - buildExampleSketch WiFiChatServer
  - buildExampleSketch WiFiPing
  - buildExampleSketch WiFiSSLClient
  - buildExampleSketch WiFiUdpNtpClient
  - buildExampleSketch WiFiUdpSendReceiveString
  - buildExampleSketch WiFiWebClient
  - buildExampleSketch WiFiWebClientRepeating
  - buildExampleSketch WiFiWebServer
  - buildExampleToolsSketch CheckFirmwareVersion
  - buildExampleToolsSketch FirmwareUpdater;
  - buildExampleToolsSketch SerialNINAPassthrough;
