name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "library.properties"
      - "examples/**"
      - "src/**"
  # Scheduled trigger checks for breakage caused by changes to external resources (libraries, platforms)
  schedule:
    # run every Saturday at 3 AM UTC
    - cron: "0 3 * * 6"
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:samd:mkrwifi1010
            platforms: |
              - name: arduino:samd
            artifact-name-suffix: arduino-samd-mkrwifi1010
          - fqbn: arduino:samd:mkrvidor4000
            platforms: |
              - name: arduino:samd
            artifact-name-suffix: arduino-samd-mkrvidor4000
          - fqbn: arduino:samd:nano_33_iot
            platforms: |
              - name: arduino:samd
            artifact-name-suffix: arduino-samd-nano_33_iot
          - fqbn: arduino:megaavr:uno2018:mode=on
            platforms: |
              - name: arduino:megaavr
            artifact-name-suffix: arduino-megaavr-uno2018
          - fqbn: arduino:mbed_nano:nanorp2040connect
            platforms: |
              - name: arduino:mbed_nano
            artifact-name-suffix: arduino-mbed_nano-nanorp2040connect

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            # Install the library from the local path.
            - source-path: ./
            # Install library dependencies.
            - name: VidorPeripherals
          sketch-paths: |
            - ./examples/
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
